name: CI-CD

on: [push, pull_request]

jobs:
  test_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            python_version: 3.7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          pip install -U pip pytest setuptools==57.4.0
          pip install Sphinx sphinx_rtd_theme
      - name: Install Package
        run: |
          python setup.py install
      - name: Run Tests
        run: |
          python setup.py test
      - name: Build Plugin
        run: |
          cd plugin_packaging
          chmod +rx build_plugin.sh
          ./build_plugin.sh
          cd ..
      - name: Make Documentation
        run: |
          make html
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: plugin_packaging/coastSHARK_plugin.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Documentation on GH-Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build